name: green
values:
  - key: baseUrl
    value: 'https://green-api.ecommerce.osbornesupremacy.com'
  - key: domain
    value: 'https://green-api.ecommerce.osbornesupremacy.com'
  - key: OrderId
    value: ''
  - key: CustomerId
    value: ''
  - key: ApiToken
    value: ''
color: 120
