name: Build, Deploy and Promote API Gateway Stages and Lambda Functions

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-infrastructure:
    name: Build Infrastructure
    uses: ./.github/workflows/.reusable-build-deploy-infrastructure.yml
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  deploy-green:
    name: Deploy Green
    needs: build-infrastructure
    uses: ./.github/workflows/.reusable-deploy-api-gateway-stage.yml
    with:
      stage-name: green
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  test-green:
    name: Test Green
    needs: deploy-green
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Run API tests on green stage
        working-directory: src/Ecommerce
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_ADDRESS: ${{ vars.GREEN_STAGE_BASE_ADDRESS }}
        run: dotnet test Ecommerce.Api.Tests/Ecommerce.Api.Tests.csproj --configuration Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: api-tests-build
          path: src/Ecommerce/**/bin

  deploy-blue:
    name: Deploy Blue
    needs: test-green
    uses: ./.github/workflows/.reusable-deploy-api-gateway-stage.yml
    with:
      stage-name: blue
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  promote-lambdas:
    name: Promote ${{ matrix.function-name }}
    needs: deploy-blue
    strategy:
      matrix:
        function-name:
          - ecommerce-create-order
          - ecommerce-get-order
          - ecommerce-update-order
          - ecommerce-delete-order
    uses: ./.github/workflows/.reusable-promote-lambda-alias.yml
    with:
      function-name: ${{ matrix.function-name }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

# Tests _could_ be run against the blue stage here. How much value would that provide?
# Teams need to make their own decision on whether the additional confidence is worth the extra time it would add to the workflow.

  cleanup-lambda-versions:
    name: Cleanup ${{ matrix.function-name }}
    needs: deploy-blue
    strategy:
      matrix:
        function-name:
          - ecommerce-create-order
          - ecommerce-get-order
          - ecommerce-update-order
          - ecommerce-delete-order
    uses: ./.github/workflows/.reusable-cleanup-unused-lambda-versions.yml
    with:
      function-name: ${{ matrix.function-name }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
