name: Build, Deploy and Promote API Gateway Stages and Lambda Functions

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  build-infrastructure:
    name: Build Infrastructure
    uses: ./.github/workflows/.reusable-build-deploy-infrastructure.yml
    with:
      tfstate_bucket: bro-tfstate
      tfstate_key: ecommerce
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  deploy-green:
    name: Deploy Green
    needs: build-infrastructure
    uses: ./.github/workflows/.reusable-deploy-api-gateway-stage.yml
    with:
      stage-name: green
      api-gateway-name: ecommerce-gateway
      wait-for-propagation: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  test-green:
    name: Test Green
    needs: deploy-green
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Run API tests on green stage
        working-directory: test/Ecommerce.Api.Tests
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_ADDRESS: ${{ vars.GREEN_STAGE_BASE_ADDRESS }}
        run: dotnet test Ecommerce.Api.Tests/Ecommerce.Api.Tests.csproj --configuration Release

  deploy-blue:
    name: Deploy Blue
    needs: test-green
    uses: ./.github/workflows/.reusable-deploy-api-gateway-stage.yml
    with:
      stage-name: blue
      api-gateway-name: ecommerce-gateway
      wait-for-propagation: true
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  promote-lambdas:
    name: Promote ${{ matrix.function-name }}
    needs: deploy-blue
    strategy:
      matrix:
        function-name:
          - ecommerce-create-order
          - ecommerce-get-order
          - ecommerce-update-order
          - ecommerce-delete-order
    uses: ./.github/workflows/.reusable-promote-lambda-alias.yml
    with:
      function-name: ${{ matrix.function-name }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

  # Whether testing on blue provides enough value for the time it takes to run the tests is a decision
  # that teams will have to make. The chances of the tests failing on blue when they passed on green are very low.

  # I am opting to run them in this reference implementation, since this deployment strategy is about about
  # being confident in the changes we are promoting to production, and testing on blue adds an extra layer of confidence.

  test-blue:
    name: Test Blue
    needs: promote-lambdas
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - name: Run API tests on blue stage
        working-directory: test/Ecommerce.Api.Tests
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          BASE_ADDRESS: ${{ vars.BLUE_STAGE_BASE_ADDRESS }}
        run: dotnet test Ecommerce.Api.Tests/Ecommerce.Api.Tests.csproj --configuration Release

  cleanup-lambda-versions:
    name: Cleanup ${{ matrix.function-name }}
    needs: test-blue
    strategy:
      matrix:
        function-name:
          - ecommerce-create-order
          - ecommerce-get-order
          - ecommerce-update-order
          - ecommerce-delete-order
    uses: ./.github/workflows/.reusable-cleanup-unused-lambda-versions.yml
    with:
      function-name: ${{ matrix.function-name }}
    secrets:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
